---
name: Build and Push Node.js image to Google Artifactory Registry
on: 
  push:
    branches: [ master ]
jobs:
  build-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nodejsapp
      PROJECT_ID: storied-fuze-385721 
    steps:
    - name: checkout
      uses: actions/checkout@v2 

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project-id: ${{ env.PROJECT_ID }} 
        export_default_credentials: true

    - name: Build docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name : Docker Image scanning with trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $IMAGE_NAME:latest
        format: table
        exit-code: 1
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'


    - name: Release tagging
      id: git-tag-increment
      run: |
        bash ./scripts/git_tag_update.sh -v major

    - name: Configure docker client
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        
    - name:
      env:
        GIT_TAG: ${{ steps.git-tag-increment.outputs.git-tag }}
      run: |
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/gar-bak-dev/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/gar-bak-dev/$IMAGE_NAME:$GIT_TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/gar-bak-dev/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/gar-bak-dev/$IMAGE_NAME:$GIT_TAG

